### ISSUE TITLE
Is it possible to add a link to a imdb page to add the movie?

### ISSUE THREAD

**Issue by romanoh** [vche/magnetarr#2]
Thank you for this, great work.

Is it possible to add a link to a imdb page to add the movie?

also, is it posssible to add some words in a imdb page movie to show it is already in radarr?

i ask because redacted as an extension like this, to use in their site, and they made it like this and works great.

**Comment by vche** [comment]
Not really, because radarr/sonarr require querying information first, before being able to send an "add" request. This means calling different APIs and can takes a couple seconds.
Magnetarr does this "on demand" when you click on the extension icon to avoid querying information needlessly, and not being intrusive on the website by inserting code to the page (which can easily incresase loading times and overload the ui).
Also, you'd miss the ability to set options (like quality or language profile, monitoring...).

For those reasons, i think magnetarr should stay an "on demand" feature.

However there is an alternative plugin called "sonarr/radarr autosearch" which insert links to imdb, that opens a search request to your radarr/sonarr, allowing you to choose the correct result and add it if you like. I tried and it works well, if you don't mind the click to open a new page. I have it installed myself, but rarely use it, i'm happier having a modal window open than a new tab

**Comment by romanoh** [comment]
ok thank you for your time.
